<?php

/**
 * The custom post types
 *
 * This class defines all custom post types.
 *
 * @since      0.1.0
 * @package    Wp_Business_Essentials
 * @subpackage Wp_Business_Essentials/includes
 * @author     Marvin Kronenfeld (WP-Styles.de) <hello@wp-styles.de>
 */
class Wp_Business_Essentials_Post_Types {

	/**
	 * Register Custom Post Type wpbe_team_member
	 *
	 * Initially generated by Generate WP at https://generatewp.com/
	 *
	 * @todo Enable custom slug / template
	 *
	 * @since  0.1.0
	 */
	public static function register_team_member() {
		$labels  = array(
			'name'                  => _x( 'Team Members', 'Post Type General Name', 'wp-business-essentials' ),
			'singular_name'         => _x( 'Team Member', 'Post Type Singular Name', 'wp-business-essentials' ),
			'menu_name'             => __( 'Team Members', 'wp-business-essentials' ),
			'name_admin_bar'        => __( 'Team Member', 'wp-business-essentials' ),
			'archives'              => __( 'Team Member Archives', 'wp-business-essentials' ),
			'attributes'            => __( 'Team Member Attributes', 'wp-business-essentials' ),
			'parent_item_colon'     => __( 'Parent Team Member:', 'wp-business-essentials' ),
			'all_items'             => __( 'All Team Members', 'wp-business-essentials' ),
			'add_new_item'          => __( 'Add Team Member', 'wp-business-essentials' ),
			'add_new'               => __( 'Add New', 'wp-business-essentials' ),
			'new_item'              => __( 'New Team Member', 'wp-business-essentials' ),
			'edit_item'             => __( 'Edit Team Member', 'wp-business-essentials' ),
			'update_item'           => __( 'Update Team Member', 'wp-business-essentials' ),
			'view_item'             => __( 'View Team Member', 'wp-business-essentials' ),
			'view_items'            => __( 'View Team Members', 'wp-business-essentials' ),
			'search_items'          => __( 'Search Team Members', 'wp-business-essentials' ),
			'not_found'             => __( 'No Team Members found', 'wp-business-essentials' ),
			'not_found_in_trash'    => __( 'No Team Members found in trash', 'wp-business-essentials' ),
			'featured_image'        => __( 'Featured Image', 'wp-business-essentials' ),
			'set_featured_image'    => __( 'Set featured image', 'wp-business-essentials' ),
			'remove_featured_image' => __( 'Remove featured image', 'wp-business-essentials' ),
			'use_featured_image'    => __( 'Use as featured image', 'wp-business-essentials' ),
			'insert_into_item'      => __( 'Insert into Team Member', 'wp-business-essentials' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Team Member', 'wp-business-essentials' ),
			'items_list'            => __( 'Items list', 'wp-business-essentials' ),
			'items_list_navigation' => __( 'Items list navigation', 'wp-business-essentials' ),
			'filter_items_list'     => __( 'Filter Team Member list', 'wp-business-essentials' ),
		);
		$rewrite = array(
			'slug'       => 'team-member',
			'with_front' => true,
			'pages'      => true,
			'feeds'      => false,
		);
		$args    = array(
			'label'               => __( 'Team Member', 'wp-business-essentials' ),
			'description'         => __( 'Meet the team', 'wp-business-essentials' ),
			'labels'              => $labels,
			'supports'            => array(
				'title',
				'editor',
				'thumbnail',
				'revisions',
//				'custom-fields',
				'page-attributes',
			),
			'taxonomies'          => array( 'wpbe_team' ),
			'hierarchical'        => true,
			'public'              => false,
			'show_ui'             => true,
			'show_in_menu'        => true,
			'menu_position'       => 25,
			'menu_icon'           => 'dashicons-businessman',
			'show_in_admin_bar'   => true,
			'show_in_nav_menus'   => false,
			'can_export'          => true,
			'has_archive'         => false,
			'exclude_from_search' => true,
			'publicly_queryable'  => false,
//			'rewrite'             => $rewrite,
			'capability_type'     => 'page',
		);
		register_post_type( 'wpbe_team_member', $args );

	}

	/**
	 * Register Custom Post Type wpbe_business
	 *
	 * Initially generated by Generate WP at https://generatewp.com/
	 *
	 * @todo Enable custom slug / template
	 * @todo Business Attributes - Provide additional, category-specific information about locations.
	 * @link http://searchengineland.com/google-mining-local-business-attributes-252283
	 *
	 * @since  0.2.0
	 */
	public static function register_business() {

		$labels  = array(
			'name'                  => _x( 'Businesses', 'Post Type General Name', 'wp-business-essentials' ),
			'singular_name'         => _x( 'Business', 'Post Type Singular Name', 'wp-business-essentials' ),
			'menu_name'             => __( 'Business', 'wp-business-essentials' ),
			'name_admin_bar'        => __( 'Business', 'wp-business-essentials' ),
			'archives'              => __( 'Business Archives', 'wp-business-essentials' ),
			'attributes'            => __( 'Business Attributes', 'wp-business-essentials' ),
			'parent_item_colon'     => __( 'Parent Item:', 'wp-business-essentials' ),
			'all_items'             => __( 'All Businesses', 'wp-business-essentials' ),
			'add_new_item'          => __( 'Add New Business', 'wp-business-essentials' ),
			'add_new'               => __( 'Add New', 'wp-business-essentials' ),
			'new_item'              => __( 'New Business', 'wp-business-essentials' ),
			'edit_item'             => __( 'Edit Business', 'wp-business-essentials' ),
			'update_item'           => __( 'Update Business', 'wp-business-essentials' ),
			'view_item'             => __( 'View Business', 'wp-business-essentials' ),
			'view_items'            => __( 'View Businesses', 'wp-business-essentials' ),
			'search_items'          => __( 'Search Business', 'wp-business-essentials' ),
			'not_found'             => __( 'No Business found', 'wp-business-essentials' ),
			'not_found_in_trash'    => __( 'No Business found in Trash', 'wp-business-essentials' ),
			'featured_image'        => __( 'Featured Image', 'wp-business-essentials' ),
			'set_featured_image'    => __( 'Set featured image', 'wp-business-essentials' ),
			'remove_featured_image' => __( 'Remove featured image', 'wp-business-essentials' ),
			'use_featured_image'    => __( 'Use as featured image', 'wp-business-essentials' ),
			'insert_into_item'      => __( 'Insert into item', 'wp-business-essentials' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Business', 'wp-business-essentials' ),
			'items_list'            => __( 'Business list', 'wp-business-essentials' ),
			'items_list_navigation' => __( 'Business list navigation', 'wp-business-essentials' ),
			'filter_items_list'     => __( 'Filter Business list', 'wp-business-essentials' ),
		);
		$rewrite = array(
			'slug'       => 'business',
			'with_front' => true,
			'pages'      => true,
			'feeds'      => true,
		);
		$args    = array(
			'label'               => __( 'Business', 'wp-business-essentials' ),
			'description'         => __( 'Post Type Description', 'wp-business-essentials' ),
			'labels'              => $labels,
			'supports'            => array(
				'title',
				'editor',
				'thumbnail',
				'revisions',
//				'custom-fields',
				'page-attributes',
			),
			'taxonomies'          => array( 'wpbe_team' ),
			'hierarchical'        => true,
			'public'              => false,
			'show_ui'             => true,
			'show_in_menu'        => true,
			'menu_position'       => 26,
			'menu_icon'           => 'dashicons-building',
			'show_in_admin_bar'   => true,
			'show_in_nav_menus'   => false,
			'can_export'          => true,
			'has_archive'         => false,
			'exclude_from_search' => true,
			'publicly_queryable'  => false,
//			'rewrite'             => $rewrite,
			'capability_type'     => 'page',
		);
		register_post_type( 'wpbe_business', $args );

	}

	/**
	 * Register Custom Taxonomy wpbe_team
	 *
	 * @todo Enable custom slug / template
	 *
	 * @since  0.1.0
	 */
	public static function register_team() {

		$labels  = array(
			'name'                       => _x( 'Teams', 'Taxonomy General Name', 'wp-business-essentials' ),
			'singular_name'              => _x( 'Team', 'Taxonomy Singular Name', 'wp-business-essentials' ),
			'menu_name'                  => __( 'Team', 'wp-business-essentials' ),
			'all_items'                  => __( 'All Items', 'wp-business-essentials' ),
			'parent_item'                => __( 'Parent Team', 'wp-business-essentials' ),
			'parent_item_colon'          => __( 'Parent Team:', 'wp-business-essentials' ),
			'new_item_name'              => __( 'New Team Name', 'wp-business-essentials' ),
			'add_new_item'               => __( 'Add New Team', 'wp-business-essentials' ),
			'edit_item'                  => __( 'Edit Team', 'wp-business-essentials' ),
			'update_item'                => __( 'Update Team', 'wp-business-essentials' ),
			'view_item'                  => __( 'View Team', 'wp-business-essentials' ),
			'separate_items_with_commas' => __( 'Separate Team Members with commas', 'wp-business-essentials' ),
			'add_or_remove_items'        => __( 'Add or remove items', 'wp-business-essentials' ),
			'choose_from_most_used'      => __( 'Choose from the most used', 'wp-business-essentials' ),
			'popular_items'              => __( 'Popular Teams', 'wp-business-essentials' ),
			'search_items'               => __( 'Search Teams', 'wp-business-essentials' ),
			'not_found'                  => __( 'No Teams found', 'wp-business-essentials' ),
			'no_terms'                   => __( 'No Teams', 'wp-business-essentials' ),
			'items_list'                 => __( 'Items list', 'wp-business-essentials' ),
			'items_list_navigation'      => __( 'Items list navigation', 'wp-business-essentials' ),
		);
		$rewrite = array(
			'slug'         => 'team',
			'with_front'   => true,
			'hierarchical' => false,
		);
		$args    = array(
			'labels'            => $labels,
			'hierarchical'      => false,
			'public'            => false,
			'show_ui'           => true,
			'show_admin_column' => true,
			'show_in_nav_menus' => false,
			'show_tagcloud'     => true,
//			'rewrite'           => $rewrite,
		);
		register_taxonomy( 'wpbe_team', array( 'wpbe_team_member', 'wpbe_business' ), $args );
	}
}
